"""adiciona cascade_delete nas tabelas de user e habit

Revision ID: 6c5a1d817e6c
Revises: 5b2a91b1169b
Create Date: 2025-11-27 20:47:47.413992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5a1d817e6c'
down_revision: Union[str, Sequence[str], None] = '5b2a91b1169b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
